name: Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  forecasts-deployment:
    runs-on: forecasts_hosted
    steps:
      - name: Depoly
        working-directory: /var/www/html/linebot-api
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          git config --local pull.ff false
          git pull origin main --autostash
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun upgrade
          bun i
          bun run build
          php artisan migrate
          php artisan optimize:clear
